### Code to merge the final dataset with all the features and training with Random Forest Classifier

**This code first merge all the feature files (DEG, PSORTb, blast, pysiochemical) together based on the id.
Target columns are the leftmost 86 columns. The final dataset is saved in a csv file.
Then Multioutput Random Forest is applied on the dataset after scaling the feature values.
Common accuracy metrices are shown for the model prediction.**

**Also a function is defined to find out the class labels (GO Terms) of the predictions. And Another function was defined to find out the description of the class labels (GO Terms Description) of the predictions**

In [2]:
import pandas as pd

In [4]:
deg_psortb_feature = pd.read_csv("/Users/zaidur/Documents/Sequence_Project/aeromonasBact/DEG_Psort_features.csv")
deg_psortb_feature

id  DEGBacteria_MaxID  DEGBacteria_totalHits  DEGArchea_MaxID  \
0      A0A068FVC1             60.571                     29           36.667   
1      A0A068FZD0             67.398                     69           60.000   
2      A0A068FZK6             52.941                     57           44.444   
3      A0A075P9Z7             93.556                    134           52.632   
4      A0A075PBX8             96.096                     65           40.541   
...           ...                ...                    ...              ...   
29770      Q7BJX9             47.962                     83           45.455   
29771      Q8UVZ1             47.619                     13           50.000   
29772      Q9L5A4             47.222                     21           44.444   
29773      R1GTS7             50.110                     29           50.000   
29774      T0PES4             50.873                     30           41.736   

       DEGArchea_totalHits  DEGEukar_MaxID  DEGEukar_totalHits  Cytoplasmic  \
0                        5          25.758                   8         2.00   
1                        8          40.541                  16         9.97   
2                        4          34.921                   8         0.00   
3                       11          28.030                  74         9.97   
4                       15          24.365                   3         9.97   
...                    ...             ...                 ...          ...   
29770                   13          59.091                  18         9.97   
29771                    7          66.250                  30         8.96   
29772                    5          37.838                  34         0.00   
29773                   18           0.000                   0         0.00   
29774                   14          42.105                   3         9.97   

       CytoplasmicMembrane  Periplasmic  ...  GO:0098542  GO:0098754  \
0                     2.00         2.00  ...           0           0   
1                     0.01         0.01  ...           0           0   
2                    10.00         0.00  ...           0           0   
3                     0.01         0.01  ...           0           0   
4                     0.01         0.01  ...           0           0   
...                    ...          ...  ...         ...         ...   
29770                 0.01         0.01  ...           0           0   
29771                 0.51         0.26  ...           0           0   
29772                 3.24         6.49  ...           0           0   
29773                 9.76         0.24  ...           0           0   
29774                 0.01         0.01  ...           0           0   

       GO:0098772  GO:0140096  GO:0140097  GO:0140098  GO:0140104  GO:0140110  \
0               0           0           0           0           0           0   
1               0           0           0           0           0           0   
2               0           0           0           0           0           0   
3               0           0           0           0           0           0   
4               0           0           0           1           0           0   
...           ...         ...         ...         ...         ...         ...   
29770           0           0           0           0           0           0   
29771           0           0           0           0           0           1   
29772           0           1           0           0           0           0   
29773           0           0           0           0           0           0   
29774           0           0           0           0           0           0   

       GO:0140657  GO:1901135  
0               0           1  
1               0           1  
2               0           0  
3               1           0  
4               0           0  
...           ...         ...  
29770           0           0  
29771      

In [7]:
physio_feature = pd.read_csv("/Users/zaidur/Documents/Sequence_Project/aeromonasBact/features_df.csv")
physio_feature

id  Molecular_Weight  Instability_Index  Isoelectric_Point  \
0      A0A068FVC1        20646.9604          36.467654           6.705830   
1      A0A068FZD0        36185.9306          27.469538           6.064857   
2      A0A068FZK6        39049.7153          41.351811           8.919346   
3      A0A075P9Z7        46953.7505          47.560143           7.054878   
4      A0A075PBX8        36645.2664          46.763964           4.906251   
...           ...               ...                ...                ...   
29770      Q7BJX9        38948.8632          35.989565           6.713674   
29771      Q8UVZ1        32647.1731          49.491667           6.809448   
29772      Q9L5A4        66634.5645          32.068606           5.699496   
29773      R1GTS7        51789.6640          40.356485           6.169952   
29774      T0PES4        49659.5660          35.945962           6.478133   

          GRAVY  Secondary_Structure_Fraction_Helix  \
0     -0.427374                            0.346369   
1     -0.147077                            0.298462   
2      0.847911                            0.417827   
3     -0.295704                            0.298329   
4     -0.202703                            0.315315   
...         ...                                 ...   
29770 -0.203478                            0.347826   
29771 -0.938542                            0.211806   
29772 -0.329647                            0.262821   
29773 -0.064644                            0.313808   
29774  0.090598                            0.301282   

       Secondary_Structure_Fraction_Turn  Secondary_Structure_Fraction_Sheet  \
0                               0.240223                            0.173184   
1                               0.209231                            0.280000   
2                               0.208914                            0.325905   
3                               0.198091                            0.298329   
4                               0.207207                            0.303303   
...                                  ...                                 ...   
29770                           0.220290                            0.220290   
29771                           0.260417                            0.246528   
29772                           0.307692                            0.246795   
29773                           0.219665                            0.326360   
29774                           0.211538                            0.335470   

       Extinction_Coefficient_1  Extinction_Coefficient_2  ...  \
0                       32430.0                   32430.0  ...   
1                       34380.0                   34755.0  ...   
2                       37930.0                   38430.0  ...   
3                       12950.0                   12950.0  ...   
4                       12950.0                   13075.0  ...   
...                         ...                       ...  ...   
29770                   51800.0                   51925.0  ...   
29771                   17880.0                   18130.0  ...   
29772                   74370.0                   74620.0  ...   
29773                   34950.0                   35075.0  ...   
29774                   33460.0                   33710.0  ...   

       _HydrophobicityD2001  _HydrophobicityD2025  _HydrophobicityD2050  \
0                     3.352                29.609                51.955   
1                     0.615                24.308                47.077   
2                     0.836                22.841                48.189   
3                     0.955                23.628                46.778   
4                     1.201                21.021                45.345   
...                     ...                   ...                   ...   
29770                 1.159                30.435                48.406   
29771                 1.389                28.819                49.653   


In [44]:
physio_feature

id  Molecular_Weight  Instability_Index  Isoelectric_Point  \
0      A0A068FVC1        20646.9604          36.467654           6.705830   
1      A0A068FZD0        36185.9306          27.469538           6.064857   
2      A0A068FZK6        39049.7153          41.351811           8.919346   
3      A0A075P9Z7        46953.7505          47.560143           7.054878   
4      A0A075PBX8        36645.2664          46.763964           4.906251   
...           ...               ...                ...                ...   
29770      Q7BJX9        38948.8632          35.989565           6.713674   
29771      Q8UVZ1        32647.1731          49.491667           6.809448   
29772      Q9L5A4        66634.5645          32.068606           5.699496   
29773      R1GTS7        51789.6640          40.356485           6.169952   
29774      T0PES4        49659.5660          35.945962           6.478133   

          GRAVY  Secondary_Structure_Fraction_Helix  \
0     -0.427374                            0.346369   
1     -0.147077                            0.298462   
2      0.847911                            0.417827   
3     -0.295704                            0.298329   
4     -0.202703                            0.315315   
...         ...                                 ...   
29770 -0.203478                            0.347826   
29771 -0.938542                            0.211806   
29772 -0.329647                            0.262821   
29773 -0.064644                            0.313808   
29774  0.090598                            0.301282   

       Secondary_Structure_Fraction_Turn  Secondary_Structure_Fraction_Sheet  \
0                               0.240223                            0.173184   
1                               0.209231                            0.280000   
2                               0.208914                            0.325905   
3                               0.198091                            0.298329   
4                               0.207207                            0.303303   
...                                  ...                                 ...   
29770                           0.220290                            0.220290   
29771                           0.260417                            0.246528   
29772                           0.307692                            0.246795   
29773                           0.219665                            0.326360   
29774                           0.211538                            0.335470   

       Extinction_Coefficient_1  Extinction_Coefficient_2       A      R  \
0                       32430.0                   32430.0   5.028  5.028   
1                       34380.0                   34755.0   9.231  5.846   
2                       37930.0                   38430.0   9.749  3.900   
3                       12950.0                   12950.0   7.399  7.399   
4                       12950.0                   13075.0   7.808  6.607   
...                         ...                       ...     ...    ...   
29770                   51800.0                   51925.0   6.957  4.928   
29771                   17880.0                   18130.0   6.944  6.250   
29772                   74370.0                   74620.0   9.135  5.609   
29773                   34950.0                   35075.0  10.879  7.741   
29774                   33460.0                   33710.0  14.103  7.051   

           N      D      C      E      Q       G      H       I       L  \
0      5.587  6.145  0.559  6.145  3.352   7.263  4.469   6.145   5.587   
1      4.308  5.538  2.154  5.538  4.308   7.077  3.077   4.615   9.231   
2      3.343  3.621  2.228  1.671  2.786   8.078  2.228  10.864  16.992   
3      4.296  5.728  0.239  9.069  2.387   6.683  1.432   7.876  10.263   
4      4.204  7.808  0.601  8.408  3.604   6.006  1.802   7.207  12.913   
...      ...    ...    ...    ...    ...     ...    ...     ...     ...   
29770  6.087  6.377  0.870  4.

In [6]:
blast_feature = pd.read_csv("/Users/zaidur/Documents/Sequence_Project/aeromonasBact/blast_feature_df.csv")
blast_feature

id  count_blast  AvgIdBlast
0      A0A068FVC1            9   96.461556
1      A0A068FZD0           12   84.911333
2      A0A068FZK6           54   90.803259
3      A0A075P9Z7          291   96.272323
4      A0A075PBX8          297   97.017865
...           ...          ...         ...
29770      V5TDW0           19   89.891474
29771      V5YM41          299   95.769060
29772      W5JXD7          143   96.887196
29773      X5C4A1           22   88.887591
29774      X5C4A6           52   90.709077

[29775 rows x 3 columns]

In [45]:
blast_feature

id  count_blast  AvgIdBlast
0      A0A068FVC1            9   96.461556
1      A0A068FZD0           12   84.911333
2      A0A068FZK6           54   90.803259
3      A0A075P9Z7          291   96.272323
4      A0A075PBX8          297   97.017865
...           ...          ...         ...
29770      V5TDW0           19   89.891474
29771      V5YM41          299   95.769060
29772      W5JXD7          143   96.887196
29773      X5C4A1           22   88.887591
29774      X5C4A6           52   90.709077

[29775 rows x 3 columns]

In [8]:
import pandas as pd

# Assuming you have the three dataframes: deg_psortb_feature, physio_feature, and blast_feature

# Merge the dataframes based on "id" column
merged_df = pd.merge(physio_feature, blast_feature, on="id", how="outer")
merged_df = pd.merge(merged_df, deg_psortb_feature, on="id", how="outer")

# Reorder the columns
column_order = ["id"] + [col for col in physio_feature.columns if col != "id"] + \
               [col for col in blast_feature.columns if col != "id"] + \
               [col for col in deg_psortb_feature.columns if col != "id"]

merged_df = merged_df[column_order]

# Print the merged dataframe
merged_df

id  Molecular_Weight  Instability_Index  Isoelectric_Point  \
0      A0A068FVC1        20646.9604          36.467654           6.705830   
1      A0A068FZD0        36185.9306          27.469538           6.064857   
2      A0A068FZK6        39049.7153          41.351811           8.919346   
3      A0A075P9Z7        46953.7505          47.560143           7.054878   
4      A0A075PBX8        36645.2664          46.763964           4.906251   
...           ...               ...                ...                ...   
29770      Q7BJX9        38948.8632          35.989565           6.713674   
29771      Q8UVZ1        32647.1731          49.491667           6.809448   
29772      Q9L5A4        66634.5645          32.068606           5.699496   
29773      R1GTS7        51789.6640          40.356485           6.169952   
29774      T0PES4        49659.5660          35.945962           6.478133   

          GRAVY  Secondary_Structure_Fraction_Helix  \
0     -0.427374                            0.346369   
1     -0.147077                            0.298462   
2      0.847911                            0.417827   
3     -0.295704                            0.298329   
4     -0.202703                            0.315315   
...         ...                                 ...   
29770 -0.203478                            0.347826   
29771 -0.938542                            0.211806   
29772 -0.329647                            0.262821   
29773 -0.064644                            0.313808   
29774  0.090598                            0.301282   

       Secondary_Structure_Fraction_Turn  Secondary_Structure_Fraction_Sheet  \
0                               0.240223                            0.173184   
1                               0.209231                            0.280000   
2                               0.208914                            0.325905   
3                               0.198091                            0.298329   
4                               0.207207                            0.303303   
...                                  ...                                 ...   
29770                           0.220290                            0.220290   
29771                           0.260417                            0.246528   
29772                           0.307692                            0.246795   
29773                           0.219665                            0.326360   
29774                           0.211538                            0.335470   

       Extinction_Coefficient_1  Extinction_Coefficient_2  ...  GO:0098542  \
0                       32430.0                   32430.0  ...           0   
1                       34380.0                   34755.0  ...           0   
2                       37930.0                   38430.0  ...           0   
3                       12950.0                   12950.0  ...           0   
4                       12950.0                   13075.0  ...           0   
...                         ...                       ...  ...         ...   
29770                   51800.0                   51925.0  ...           0   
29771                   17880.0                   18130.0  ...           0   
29772                   74370.0                   74620.0  ...           0   
29773                   34950.0                   35075.0  ...           0   
29774                   33460.0                   33710.0  ...           0   

       GO:0098754  GO:0098772  GO:0140096  GO:0140097  GO:0140098  GO:0140104  \
0               0           0           0           0           0           0   
1               0           0           0           0           0           0   
2               0           0           0           0           0           0   
3               0           0           0           0           0           0   
4               0           0           0           0           1           0   
...           ...         ...         ...    

In [9]:
pd.set_option('display.max_columns', None) # This will display all columns
#reset
# pd.reset_option('display.max_columns')

pd.set_option('display.max_colwidth', None)  # Display full text in columns
#reset
# pd.reset_option('display.max_colwidth')

In [50]:
merged_df

id  Molecular_Weight  Instability_Index  Isoelectric_Point  \
0      A0A068FVC1        20646.9604          36.467654           6.705830   
1      A0A068FZD0        36185.9306          27.469538           6.064857   
2      A0A068FZK6        39049.7153          41.351811           8.919346   
3      A0A075P9Z7        46953.7505          47.560143           7.054878   
4      A0A075PBX8        36645.2664          46.763964           4.906251   
...           ...               ...                ...                ...   
29770      Q7BJX9        38948.8632          35.989565           6.713674   
29771      Q8UVZ1        32647.1731          49.491667           6.809448   
29772      Q9L5A4        66634.5645          32.068606           5.699496   
29773      R1GTS7        51789.6640          40.356485           6.169952   
29774      T0PES4        49659.5660          35.945962           6.478133   

          GRAVY  Secondary_Structure_Fraction_Helix  \
0     -0.427374                            0.346369   
1     -0.147077                            0.298462   
2      0.847911                            0.417827   
3     -0.295704                            0.298329   
4     -0.202703                            0.315315   
...         ...                                 ...   
29770 -0.203478                            0.347826   
29771 -0.938542                            0.211806   
29772 -0.329647                            0.262821   
29773 -0.064644                            0.313808   
29774  0.090598                            0.301282   

       Secondary_Structure_Fraction_Turn  Secondary_Structure_Fraction_Sheet  \
0                               0.240223                            0.173184   
1                               0.209231                            0.280000   
2                               0.208914                            0.325905   
3                               0.198091                            0.298329   
4                               0.207207                            0.303303   
...                                  ...                                 ...   
29770                           0.220290                            0.220290   
29771                           0.260417                            0.246528   
29772                           0.307692                            0.246795   
29773                           0.219665                            0.326360   
29774                           0.211538                            0.335470   

       Extinction_Coefficient_1  Extinction_Coefficient_2       A      R  \
0                       32430.0                   32430.0   5.028  5.028   
1                       34380.0                   34755.0   9.231  5.846   
2                       37930.0                   38430.0   9.749  3.900   
3                       12950.0                   12950.0   7.399  7.399   
4                       12950.0                   13075.0   7.808  6.607   
...                         ...                       ...     ...    ...   
29770                   51800.0                   51925.0   6.957  4.928   
29771                   17880.0                   18130.0   6.944  6.250   
29772                   74370.0                   74620.0   9.135  5.609   
29773                   34950.0                   35075.0  10.879  7.741   
29774                   33460.0                   33710.0  14.103  7.051   

           N      D      C      E      Q       G      H       I       L  \
0      5.587  6.145  0.559  6.145  3.352   7.263  4.469   6.145   5.587   
1      4.308  5.538  2.154  5.538  4.308   7.077  3.077   4.615   9.231   
2      3.343  3.621  2.228  1.671  2.786   8.078  2.228  10.864  16.992   
3      4.296  5.728  0.239  9.069  2.387   6.683  1.432   7.876  10.263   
4      4.204  7.808  0.601  8.408  3.604   6.006  1.802   7.207  12.913   
...      ...    ...    ...    ...    ...     ...    ...     ...     ...   
29770  6.087  6.377  0.870  4.

In [51]:
merged_df.to_csv("merged_df.csv", index=False)

In [18]:
merged_df_final = merged_df.drop('id', axis=1)

In [19]:
merged_df_final

Molecular_Weight  Instability_Index  Isoelectric_Point     GRAVY  \
0            20646.9604          36.467654           6.705830 -0.427374   
1            36185.9306          27.469538           6.064857 -0.147077   
2            39049.7153          41.351811           8.919346  0.847911   
3            46953.7505          47.560143           7.054878 -0.295704   
4            36645.2664          46.763964           4.906251 -0.202703   
...                 ...                ...                ...       ...   
29770        38948.8632          35.989565           6.713674 -0.203478   
29771        32647.1731          49.491667           6.809448 -0.938542   
29772        66634.5645          32.068606           5.699496 -0.329647   
29773        51789.6640          40.356485           6.169952 -0.064644   
29774        49659.5660          35.945962           6.478133  0.090598   

       Secondary_Structure_Fraction_Helix  Secondary_Structure_Fraction_Turn  \
0                                0.346369                           0.240223   
1                                0.298462                           0.209231   
2                                0.417827                           0.208914   
3                                0.298329                           0.198091   
4                                0.315315                           0.207207   
...                                   ...                                ...   
29770                            0.347826                           0.220290   
29771                            0.211806                           0.260417   
29772                            0.262821                           0.307692   
29773                            0.313808                           0.219665   
29774                            0.301282                           0.211538   

       Secondary_Structure_Fraction_Sheet  Extinction_Coefficient_1  \
0                                0.173184                   32430.0   
1                                0.280000                   34380.0   
2                                0.325905                   37930.0   
3                                0.298329                   12950.0   
4                                0.303303                   12950.0   
...                                   ...                       ...   
29770                            0.220290                   51800.0   
29771                            0.246528                   17880.0   
29772                            0.246795                   74370.0   
29773                            0.326360                   34950.0   
29774                            0.335470                   33460.0   

       Extinction_Coefficient_2       A      R      N      D      C      E  \
0                       32430.0   5.028  5.028  5.587  6.145  0.559  6.145   
1                       34755.0   9.231  5.846  4.308  5.538  2.154  5.538   
2                       38430.0   9.749  3.900  3.343  3.621  2.228  1.671   
3                       12950.0   7.399  7.399  4.296  5.728  0.239  9.069   
4                       13075.0   7.808  6.607  4.204  7.808  0.601  8.408   
...                         ...     ...    ...    ...    ...    ...    ...   
29770                   51925.0   6.957  4.928  6.087  6.377  0.870  4.348   
29771                   18130.0   6.944  6.250  5.208  6.250  1.389  6.597   
29772                   74620.0   9.135  5.609  6.891  6.891  0.641  2.564   
29773                   35075.0  10.879  7.741  2.301  5.021  0.418  7.113   
29774                   33710.0  14.103  7.051  1.496  5.556  0.855  5.128   

           Q       G      H       I       L      K      M      F      P  \
0      3.352   7.263  4.469   6.145   5.587  6.704  0.559  8.380  3.911   
1      4.308   7.077  3.077   4.615   9.231  3.692  4.000  4.000  3.385   
2      2.786   8.078  2.228  10.864  16.992  3.064  4.178  4.457  5.014   
3      2.387   6.683  1.432   7.876  10.263  7.399  3.1

In [49]:
merged_df_final.to_csv("merged_df_final.csv", index=False)

In [20]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler


# Splitting into features and targets
X = merged_df_final.iloc[:, 0:195]  # Features
y = merged_df_final.iloc[:, 195:]  # Targets

# Scaling data
scaler = StandardScaler()
X = scaler.fit_transform(X)

# Splitting into train and test
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [27]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.multioutput import MultiOutputClassifier

# RandomForest model
model_rf = RandomForestClassifier(n_estimators=100, random_state=42)

# Make it a multioutput classifier
multilabel_rf = MultiOutputClassifier(model_rf)

# Train
multilabel_rf.fit(X_train, y_train)

# Predict
y_pred = multilabel_rf.predict(X_test)

In [78]:
y_pred.shape

(5955, 86)

In [69]:
target_cols = y.columns
target_list = list(target_cols)

import numpy as np

# Get labels
labels = target_cols[np.where(y_pred[0] == 1)]

print(labels)

Index(['GO:0003674', 'GO:0008150', 'GO:0016853'], dtype='object')


In [83]:
"""
Find the prediction class labels
"""

import numpy as np

#import the main dataset (without id column) to get the target labels in the column names
dataset_df = pd.read_csv("merged_df_final.csv")
target_cols = merged_df_final.iloc[:, 195:].columns  #Last 86 colums are the target columns of the main dataset

#y_pred is the predicted array. 
def prediction_label(y_pred, target_cols):
    labels_list = []
    for pred in y_pred:
        labels = list(target_cols[np.where(pred == 1)])
        labels_list.append(labels)
        
    return labels_list

y_pred_labels = prediction_label(y_pred, target_cols)
y_pred_labels

[['GO:0003674', 'GO:0008150', 'GO:0016853'],
 ['GO:0003674', 'GO:0003677', 'GO:0006310', 'GO:0016787', 'GO:0140097'],
 ['GO:0003674', 'GO:0003723', 'GO:0005575', 'GO:0006399', 'GO:0140098'],
 ['GO:0003674', 'GO:0005886', 'GO:0006629', 'GO:0006790', 'GO:0016787'],
 ['GO:0005886', 'GO:0008150', 'GO:0016740'],
 ['GO:0003674',
  'GO:0006575',
  'GO:0006766',
  'GO:0016829',
  'GO:0016874',
  'GO:0055086',
  'GO:1901135'],
 ['GO:0003674', 'GO:0006399', 'GO:0140098'],
 ['GO:0005618',
  'GO:0005886',
  'GO:0005975',
  'GO:0006629',
  'GO:0016740',
  'GO:1901135'],
 ['GO:0003674',
  'GO:0005215',
  'GO:0005575',
  'GO:0005886',
  'GO:0016874',
  'GO:0140657'],
 ['GO:0016740'],
 ['GO:0003674', 'GO:0003677', 'GO:0008150', 'GO:0140097'],
 ['GO:0003674', 'GO:0005575', 'GO:0006399', 'GO:0016491', 'GO:1901135'],
 ['GO:0005575', 'GO:0006520', 'GO:0016740', 'GO:0016787', 'GO:0016829'],
 ['GO:0003674',
  'GO:0005215',
  'GO:0005575',
  'GO:0005886',
  'GO:0016787',
  'GO:0016874',
  'GO:0140657'],
 ['G

In [97]:
"""
Find the prediction class labels along with their description
"""

import numpy as np

#import the GO Term description file
goDescription_df = pd.read_csv("go_parent_data.csv")

#import the main dataset (without id column) to get the target labels in the column names
dataset_df = pd.read_csv("merged_df_final.csv")
target_cols = merged_df_final.iloc[:, 195:].columns  #Last 86 colums are the target columns of the main dataset

#y_pred is the predicted array. 
def prediction_label_description(y_pred, target_cols, goDescription_df):
    labels_list = []
    for pred in y_pred:
        labels_dict = {}  #Dictionary to hold the GO Term with their description
        labels = list(target_cols[np.where(pred == 1)])
        for label in labels:
            description= goDescription_df[goDescription_df['go_id']==label]['name'].values
            if len(description)>0: 
                labels_dict[label] = description[0]
            else:
                labels_dict[label] = None
        labels_list.append(labels_dict)
        
    return labels_list

y_pred_labels = prediction_label_description(y_pred, target_cols, goDescription_df)
y_pred_labels

[{'GO:0003674': 'Other Molecular Function',
  'GO:0008150': 'Other Biological Process',
  'GO:0016853': 'isomerase activity'},
 {'GO:0003674': 'Other Molecular Function',
  'GO:0003677': 'dna binding',
  'GO:0006310': 'DNA recombination',
  'GO:0016787': 'hydrolase activity',
  'GO:0140097': 'catalytic activity, acting on DNA'},
 {'GO:0003674': 'Other Molecular Function',
  'GO:0003723': 'rna binding',
  'GO:0005575': 'Other Cellular Component',
  'GO:0006399': 'tRNA metabolic process',
  'GO:0140098': 'catalytic activity, acting on RNA'},
 {'GO:0003674': 'Other Molecular Function',
  'GO:0005886': 'plasma membrane',
  'GO:0006629': 'lipid metabolic process',
  'GO:0006790': 'sulfur compound metabolic process',
  'GO:0016787': 'hydrolase activity'},
 {'GO:0005886': 'plasma membrane',
  'GO:0008150': 'Other Biological Process',
  'GO:0016740': 'transferase activity'},
 {'GO:0003674': 'Other Molecular Function',
  'GO:0006575': 'cellular modified amino acid metabolic process',
  'GO:0006

In [85]:
goDescription_df = pd.read_csv("go_parent_data.csv")
goDescription_df

go_id                              name               class
0    GO:0001618           virus receptor activity  molecular function
1    GO:0003677                       dna binding  molecular function
2    GO:0003723                       rna binding  molecular function
3    GO:0003744       cytoskeletal motor activity  molecular function
4    GO:0003824                catalytic activity  molecular function
..          ...                               ...                 ...
139  GO:0030312  external encapsulating structure  cellular component
140  GO:0031012              extracellular matrix  cellular component
141  GO:0031410               cytoplasmic vesicle  cellular component
142  GO:0043226                         organelle  cellular component
143  GO:0005575          Other Cellular Component  cellular component

[144 rows x 3 columns]

In [96]:
goDescription_df[goDescription_df['go_id']=='GO:0003677']['name'].values

array(['dna binding'], dtype=object)

In [82]:
len(y_pred_labels)

5955

In [29]:
from sklearn.metrics import accuracy_score, jaccard_score, f1_score, hamming_loss

# Convert to binary format
y_test_binary = (y_test > 0).astype(int)
y_pred_binary = (y_pred > 0).astype(int)

# Compute metrics
accuracy = accuracy_score(y_test_binary, y_pred_binary)
jaccard = jaccard_score(y_test_binary, y_pred_binary, average='samples')
f1 = f1_score(y_test_binary, y_pred_binary, average='samples')
hamming = hamming_loss(y_test_binary, y_pred_binary)

print(f"Accuracy: {accuracy}")
print(f"Jaccard score: {jaccard}")
print(f"F1 score: {f1}")
print(f"Hamming loss: {hamming}")

Accuracy: 0.9289672544080605
Jaccard score: 0.9663945863819919
F1 score: 0.9749723473652945
Hamming loss: 0.001853045125261164


In [42]:
from sklearn.metrics import precision_score, recall_score, confusion_matrix, roc_auc_score

#y_test to numpy arrays
y_test_np = y_test.to_numpy()

#Precision and Recall
precision = precision_score(y_test, y_pred, average='samples')
recall = recall_score(y_test, y_pred, average='samples')

print("Precision: ", precision)
print("Recall: ", recall)

# Confusion Matrix
for i in range(y_test_np.shape[1]):
    print(f"Confusion matrix for label {i}:")
    print(confusion_matrix(y_test_np[:, i], y_pred[:, i]))


Precision:  0.9903174603174604
Recall:  0.9686911213611465
Confusion matrix for label 0:
[[5927    0]
 [   0   28]]
Confusion matrix for label 1:
[[5951    0]
 [   4    0]]
Confusion matrix for label 2:
[[1385   40]
 [   5 4525]]
Confusion matrix for label 3:
[[5528    0]
 [  14  413]]
Confusion matrix for label 4:
[[5447    0]
 [  23  485]]
Confusion matrix for label 5:
[[5944    0]
 [   2    9]]
Confusion matrix for label 6:
[[5882    0]
 [   3   70]]
Confusion matrix for label 7:
[[5907    1]
 [   3   44]]
Confusion matrix for label 8:
[[2881   21]
 [  22 3031]]
Confusion matrix for label 9:
[[5932    0]
 [   3   20]]
Confusion matrix for label 10:
[[5954    0]
 [   1    0]]
Confusion matrix for label 11:
[[5871    0]
 [   3   81]]
Confusion matrix for label 12:
[[5954    0]
 [   1    0]]
Confusion matrix for label 13:
[[5859    1]
 [   2   93]]
Confusion matrix for label 14:
[[5954    0]
 [   1    0]]
Confusion matrix for label 15:
[[5955]]
Confusion matrix for label 16:
[[5954    

/Users/zaidur/opt/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in samples with no predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [84]:
#Save the trained model in pickle

import pickle

# Save the trained model to a file with model paramater, n_estimators=100, random_state=42
with open('randomForest_100_42.pkl', 'wb') as file:
    pickle.dump(multilabel_rf, file)
    

# # Load the model from the file
# with open('randomForest_100_42.pkl', 'rb') as file:
#     loaded_model = pickle.load(file)

# # Use the loaded model to make predictions
# predictions = loaded_model.predict(X_test)